# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

DEMO_MERCHANT_NAMES = [
  "NexGen Innovations",
  "AquaVibe Solutions",
  "TerraGraph Technologies",
  "LunaTech Industries",
  "Sustainify Corp.",
  "CleverCloud Services",
  "UrbanNest Designs",
  "Fusionary Foods",
  "Zenith Health Partners",
  "PixelWave Media",
  "QuantumSphere Dynamics",
  "EchoVerse Studios",
  "BrightPath Consulting",
  "TrueNorth Logistics",
  "BioSphere Innovations",
  "Crestwood Ventures",
  "FrostFlare Technologies",
  "SolarPulse Energy",
  "VerdeVista Agriculture",
  "Lighthouse Legal Group",
  "Cobalt Communications",
  "Artisan Elements",
  "NaturaLife Labs",
  "Elevate HR Solutions",
  "Crescendo Music Works",
  "UrbanSync Systems",
  "Infusion Analytics",
  "StellarSky Aerospace",
  "EcoTide Concepts",
  "MavenHouse Realty",
  "VividStep Productions",
  "NextWave Technologies",
  "QuantumLeaf Investments",
  "Sylvan Dynamics",
  "Oasis Wellness Center",
  "Pinnacle Software Co.",
  "Evolve Digital Strategies",
  "BrightForge Studios",
  "Bamboo Grove Industries",
  "Catalyst Creatives",
  "Crimson Tiger Media",
  "Horizon Space Systems",
  "PrismShift Consulting",
  "Lush Life Organics",
  "MindSpark Technologies",
  "Radial Network Solutions",
  "Insightful Games",
  "ClearRipple Communications",
  "Galactic Insights",
  "TerraNova Construction",
  "Aetherial Design Co.",
  "TechBloom Systems",
  "Summit Strategy Group",
  "Urban Euphoria",
  "Heritage Treasures",
  "Icicle Innovations",
  "NobleQuest Financial",
  "Thrive Market Solutions",
  "Campfire Visuals",
  "VentureLink Investments",
  "Aspire Educational Services",
  "Whispering Pines Retreat",
  "Vortex Media Group",
  "Radiant Energy Technologies",
  "Guardian IT Services",
  "EchoPoint Consulting",
  "Vital Essence Labs",
  "AuraHome Solutions",
  "Epicenter Marketing",
  "Sage & Stone Interiors",
  "FableForge Games",
  "Fleetwood Logistics",
  "Revolutionary Robotics",
  "Skyline Property Management",
  "SkyHigh Enterprises",
  "Mindful Mission Consulting",
  "Park and Play Events",
  "OpenCanvas Art Studio",
  "Velocity Sports Equipment",
  "BluePlanet Waste Management",
  "Infinite Loop Technologies",
  "Charisma Branding Agency",
  "EchoFall Productions",
  "Starboard Financial Group",
  "Impulse Energy Solutions",
  "JazzedUp Media",
  "GreenCrest Strategies",
  "Enlighten Health Solutions",
  "Wildwood Agritech",
  "Beacon Insights Group",
  "PureHarmony Wellness",
  "Evergreen Tech Solutions",
  "Sapphire Crafters",
  "ThriveSpace Technologies",
  "Hearty Roots Organics",
  "FreshStart Cleaners",
  "Polaris Marketing Group",
  "Litmus Technologies",
  "Dynamic Horizons",
  "Wavelength Systems",
  "SwiftStone Realty",
  "Breezy Path Travel",
  "Blooming Ideas Consulting",
  "Galaxy Media Works",
  "Crescent City Ventures",
  "Nimble Innovations",
  "Ascendant BioSolutions",
  "Wholesome Bites Cafe",
  "Cobalt Wave Analytics",
  "Silverline Construction",
  "Intersect Solutions",
  "TrueVista Technologies",
  "Halcyon Ventures"
].freeze

Merchant.insert_all!(DEMO_MERCHANT_NAMES.map { |e| { slug: e.parameterize } })
